// Code generated by goctl. DO NOT EDIT!
// Source: sum.proto

package sum

import (
	"context"

	"grpc-restufl/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Numbers    = pb.Numbers
	SumReponse = pb.SumReponse
	SumRequest = pb.SumRequest

	Sum interface {
		Add(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumReponse, error)
	}

	defaultSum struct {
		cli zrpc.Client
	}
)

func NewSum(cli zrpc.Client) Sum {
	return &defaultSum{
		cli: cli,
	}
}

func (m *defaultSum) Add(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumReponse, error) {
	client := pb.NewSumClient(m.cli.Conn())
	return client.Add(ctx, in, opts...)
}
